# Generated by Django 4.2.7 on 2023-11-25 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosComCamposAdicionais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagemPerfil', models.FileField(blank=True, null=True, upload_to='img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
