# Generated by Django 4.2.7 on 2023-11-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_codigo_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
