# Generated by Django 4.2.7 on 2023-11-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_turma_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.DeleteModel(
            name='Codigo',
        ),
    ]
