# Generated by Django 4.2.7 on 2023-11-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemForum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remetente', models.CharField(blank=True, max_length=100, null=True)),
                ('imagemPerfil', models.FileField(blank=True, null=True, upload_to='img')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
