# Generated by Django 4.2.7 on 2023-11-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_projeto_anotacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='anotacoes',
            field=models.TextField(blank=True, default='Este projeto não possui descrição', max_length=600, null=True),
        ),
    ]
