# Generated by Django 4.2.7 on 2023-11-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_projeto_anotacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, default='Sprint', max_length=20, null=True)),
                ('dataInicio', models.DateField(auto_now_add=True, null=True)),
                ('dataEntrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Criada', max_length=20)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projeto')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
        ),
    ]
