# Generated by Django 4.2.3 on 2023-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no_reload', '0002_mensagem_remove_profile_bio_remove_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
