# Generated by Django 5.1.4 on 2024-12-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_categoria_produto_catgoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='catgoria',
            new_name='categoria',
        ),
    ]
